version: '3'
services:
  frontend:
    build: .
    environment:
      API_URL_WP: http://192.168.144.6:80/wp-json/
      API_URL_AUTH: http://192.168.144.6:80/api/
      GRAPHQL_URL: http://192.168.144.6:80/graphql/
      HTTPS: 'false'
      APP_HOST: http://localhost
      APP_PORT: '3000'
      CMS_PATH: ../src/server/static
      STATIC_PATH: ../src/client/assets
      NODE_ENV: production
    networks:
      - web
      - backend
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_webgateway
      - traefik.http.services.frontend.loadbalancer.server.port=3000
      - traefik.http.routers.top_fashion_frontend.rule=Host(`frontend.docker.localhost`)
      - traefik.http.routers.top_fashion_frontend.entrypoints=https
      - traefik.http.routers.top_fashion_frontend.tls.certresolver=default

networks:
  web:
    external:
      name: proxy_webgateway
  backend:
    driver: bridge
