version: '3'
services:
  frontend:
    image: 12evgen/topfashion-frontend:1.0.1
    container_name: "topfashion-frontend"
    ports:
      - '3000:3000'
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
